---

- name: Gather facts
  hosts: all
  gather_facts: True

  tasks:
    - name: List VMs
      xenserver_guest_info:
        hostname: "vms1"
        username: "root"
        password: "Qw3rty02@home"
      delegate_to: localhost
      register: returnedData
