---

- name: Gather facts
  hosts: all
  gather_facts: True

  tasks:
    - name: List VMs
      xenserver_guest_info:
        hostname: "vms1"
        username: "root"
        password: "Qw3rty02@home"
        uuid: "af7d7bd8-1659-bf16-56cf-8442d0fa1045"
      delegate_to: localhost
      register: returnedData
