---

- name: Gather facts from xenserver
  hosts: all
  gather_facts: True
  
  tasks:
    - name: List VMs
      xenserver_facts:
      register: returnedData
      
- name: Print running VMs
  debug:
    msg: "{{ item }}"
  with_items: "{{ xs_vms.keys() }}"
  when: xs_vms[item]['power_state'] == "*"
