---

- name: Gather facts from xenserver
  hosts: all
  gather_facts: True
  
  tasks:
    - name: List VMs
      xenserver_facts:
        hostname: "vms1"
        username: "root"
        password: "Qw3rty02@home"
      register: returnedData
